version: '2.1'
services:
  beanstalksvc:
    image: schickling/beanstalkd:latest
    container_name: beanstalksvc
    restart: always
    networks:
      - health-nlp-network   
    ports:
      - "127.0.0.1:11300:11300"
  elasticsvc:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsvc
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=somepass
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1024m
    memswap_limit: 1024m
    privileged: false
    restart: always
    networks:
      - health-nlp-network   
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
  health-nlp:
    build: .
    container_name: health-nlp 
    volumes:
      - .:/usr/src/app
    networks:
      - health-nlp-network
    restart: always
    depends_on:
      - beanstalksvc
      - elasticsvc


networks:
  health-nlp-network:
    external:
      name: health-nlp-network 
